development:
  access_key_id: YOURSECRETACCESSID
  secret_access_key: YOUR-secRE/TACCe\ssKEy
  bucket: my-bucket-development
production:
  access_key_id: YOURSECRETACCESSID
  secret_access_key: YOUR-secRE/TACCe\ssKEy
  bucket: my-bucket-production
test:
  access_key_id: YOURSECRETACCESSID
  secret_access_key: YOUR-secRE/TACCe\ssKEy
  bucket: my-bucket-test
cucumber:
  access_key_id: YOURSECRETACCESSID
  secret_access_key: YOUR-secRE/TACCe\ssKEy
  bucket: my-bucket-test